name:
  FunGoEnv

services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql
    networks:
      - FunGo
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=861214959
    volumes:
      - fungo_data:/var/lib/mysql
  redis:
    container_name: redis
    restart: always
    image: bitnami/redis
    networks:
      - FunGo
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=861214959
  srs:
    container_name: srs
    restart: always
    image: ossrs/srs
    networks:
      - FunGo
    ports:
      - "10080:10080"
      - "1935:1935"
      - "1985:1985"
      - "5060:5060"
      - "8000:8000"
      - "8080:8080"
      - "9000:9000"


volumes:
  fungo_data:

networks:
  FunGo: